QUERY = "remote job with visa support"
VACANCIES = [
    "Senior Python Developer with FastAPI experience, fully remote position, competitive salary.",
    "Backend Engineer (Python/Django) — work from anywhere in the world, flexible hours.",
    "Data Engineer needed: ClickHouse, Kafka, dbt. Hybrid office in Berlin, 3 days on-site.",
    "Looking for a Go developer to build microservices. Strictly on-site in London, no remote.",
    "Machine Learning Engineer, PyTorch and LLM fine-tuning, distributed team across EU timezones.",
    "Frontend React developer, TypeScript, Next.js. Remote within Europe only.",
    "DevOps Engineer — Kubernetes, Terraform, AWS. Office-based role in Munich, relocation package provided.",
    "Full-stack JavaScript engineer (Node.js + Vue). Remote-first company, async culture.",
    "Junior QA Automation Engineer, Selenium and Playwright. On-site in Warsaw, no visa sponsorship available.",
    "Site Reliability Engineer with strong Linux background, 24/7 on-call rotation, hybrid in Amsterdam.",
    "AI Research Scientist focused on RAG systems and vector databases. Distributed team, work from any location.",
    "Database Administrator for PostgreSQL and ClickHouse clusters, remote position, EU residency required.",
    "Solidity smart contract developer, DeFi protocol, fully decentralized team — work from anywhere.",
    "iOS Engineer (Swift, SwiftUI), Apple ecosystem expert. Hybrid in Cupertino, relocation supported.",
    "Technical Writer for developer documentation, Python and API references. Remote, any timezone.",
    "Product Manager with B2B SaaS background, on-site in New York, visa sponsorship offered for the right candidate.",
    "Cybersecurity Analyst — SIEM, threat hunting, incident response. Remote within US only.",
    "Junior Data Analyst with SQL and Tableau skills. Office-based in Singapore, entry-level salary.",
    "Embedded systems engineer (C/C++, RTOS), automotive industry. On-site in Stuttgart, relocation paid.",
    "Cloud Architect (GCP, multi-region), 10+ years experience. Remote-friendly, contract or full-time.",
]
