version: "3.8"

services:

  db:
    image: pgvector/pgvector:pg17
    environment:
      - POSTGRES_ROOT_PASSWORD=qwe123
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=qwe123
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/01-init.sql